[project]
name = "epicsdev_ps_caen_fastps"
version = "0.0.3"
authors = [
  { name="Andrey Sukhanov", email="sukhanov@bnl.gov" },
]
description = "EPICS PVAccess server for CAEN FAST-PS power supplies"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "epicsdev>=1.0.2",
]

[project.optional-dependencies]
opi = [
  "phoebusgen",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

"Homepage" = "https://github.com/eicorg/epicsdev_ps_caen_fastps"
"Bug Tracker" = "https://github.com/eicorg/epicsdev_ps_caen_fastps"